// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`

/// 适配器名字。没有适配器时抛异常。
String bleAdapterName() => RustLib.instance.api.crateApiBleBleAdapterName();

/// 当前适配器占用状态。
BleMode bleMode() => RustLib.instance.api.crateApiBleBleMode();

/// 开始扫描。返回的 Dart `Stream` 每轮 burst 产出一条事件(已去重)。
///
/// ⚠ **设备平时是完全静默的** —— 固件只在单击按键后播
///   `BLE_BEACON_ADV_EVENTS` 个广播事件。所以"扫描已启动但一直没有数据"是
///   正常状态, 不是故障, UI 上必须写清楚, 否则用户会以为工具坏了。
///
/// ⚠ Windows 下收包率天然很低(每 ~1.3s 才开一次扫描窗口, 而一轮 burst 只有
///   1.5s)。这是系统限制, 见 `crate::ble` 的文件头。真正的数据采集应该走
///   连接后的 `REC_READ`, 不要指望扫描收全。
Stream<BleAdvEvent> bleScanStart() =>
    RustLib.instance.api.crateApiBleBleScanStart();

/// 停止扫描。未在扫描时安全。
void bleScanStop() => RustLib.instance.api.crateApiBleBleScanStop();

/// 一条已解析的广播(去重后, 每轮 burst 只上报一条)。
class BleAdvEvent {
  final String? mac;
  final int? rssi;

  /// 厂商自定义段原始字节(不含 Company ID), 供 UI 做 hexdump。
  final Uint8List raw;

  /// 解析是否成功。
  final bool ok;

  /// 解析失败原因(`ok == false` 时)。
  final String? error;
  final int version;
  final int deviceId;

  /// 单击计数器。同一轮 burst 内不变 —— 本字段即去重依据。
  final int counter;
  final int battMv;

  /// 三通道原始计数。
  ///
  /// ⚠ 三通道增益不同(ch0=128, ch1=32, ch2=128)且载荷里不携带增益,
  ///   UI 上直接比较三者数值是错的。实测灵敏度
  ///   ch0≈192.2 / ch1≈49.3 / ch2≈−199.9 counts/g(注意 ch2 为负)。
  final Int32List ch;

  const BleAdvEvent({
    this.mac,
    this.rssi,
    required this.raw,
    required this.ok,
    this.error,
    required this.version,
    required this.deviceId,
    required this.counter,
    required this.battMv,
    required this.ch,
  });

  @override
  int get hashCode =>
      mac.hashCode ^
      rssi.hashCode ^
      raw.hashCode ^
      ok.hashCode ^
      error.hashCode ^
      version.hashCode ^
      deviceId.hashCode ^
      counter.hashCode ^
      battMv.hashCode ^
      ch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BleAdvEvent &&
          runtimeType == other.runtimeType &&
          mac == other.mac &&
          rssi == other.rssi &&
          raw == other.raw &&
          ok == other.ok &&
          error == other.error &&
          version == other.version &&
          deviceId == other.deviceId &&
          counter == other.counter &&
          battMv == other.battMv &&
          ch == other.ch;
}

/// 适配器当前被谁占用。与 [`ble::Mode`] 一一对应。
enum BleMode {
  /// 空闲。
  idle,

  /// 正在扫描广播。
  scanning,

  /// 已连接(命令协议可用)。
  connected,
}
